CATEGORIES = [
    {"slug": "technology", "name_id": "Teknologi/IT", "name_en": "Technology/IT"},
    {"slug": "data_science_ai", "name_id": "Data Science/AI", "name_en": "Data Science/AI"},
    {"slug": "software_engineering", "name_id": "Rekayasa Perangkat Lunak", "name_en": "Software Engineering"},
    {"slug": "finance_accounting", "name_id": "Keuangan/Akuntansi", "name_en": "Finance/Accounting"},
    {"slug": "banking", "name_id": "Perbankan", "name_en": "Banking"},
    {"slug": "fintech", "name_id": "Fintech", "name_en": "Fintech"},
    {"slug": "marketing", "name_id": "Pemasaran", "name_en": "Marketing"},
    {"slug": "digital_marketing", "name_id": "Pemasaran Digital", "name_en": "Digital Marketing"},
    {"slug": "sales", "name_id": "Penjualan", "name_en": "Sales"},
    {"slug": "human_resources", "name_id": "Sumber Daya Manusia", "name_en": "Human Resources"},
    {"slug": "customer_service", "name_id": "Layanan Pelanggan", "name_en": "Customer Service"},
    {"slug": "administration", "name_id": "Administrasi/Sekretaris", "name_en": "Administration"},
    {"slug": "engineering", "name_id": "Teknik (Sipil/Mesin/Elektro)", "name_en": "Engineering (Civil/Mech/Elec)"},
    {"slug": "manufacturing", "name_id": "Manufaktur/Produksi", "name_en": "Manufacturing/Production"},
    {"slug": "quality_assurance", "name_id": "Penjaminan Mutu", "name_en": "Quality Assurance"},
    {"slug": "logistics", "name_id": "Logistik/Rantai Pasok", "name_en": "Logistics/Supply Chain"},
    {"slug": "healthcare", "name_id": "Kesehatan/Medis", "name_en": "Healthcare/Medical"},
    {"slug": "pharmaceutical", "name_id": "Farmasi", "name_en": "Pharmaceutical"},
    {"slug": "education", "name_id": "Pendidikan/Pengajaran", "name_en": "Education/Teaching"},
    {"slug": "research", "name_id": "Penelitian & Pengembangan", "name_en": "Research & Development"},
    {"slug": "legal", "name_id": "Hukum", "name_en": "Legal"},
    {"slug": "creative_design", "name_id": "Kreatif/Desain", "name_en": "Creative/Design"},
    {"slug": "media", "name_id": "Media/Jurnalistik", "name_en": "Media/Journalism"},
    {"slug": "hospitality", "name_id": "Perhotelan/Pariwisata", "name_en": "Hospitality/Tourism"},
    {"slug": "food_beverage", "name_id": "Makanan & Minuman", "name_en": "Food & Beverage"},
    {"slug": "retail", "name_id": "Ritel", "name_en": "Retail"},
    {"slug": "ecommerce", "name_id": "E-commerce", "name_en": "E-commerce"},
    {"slug": "real_estate", "name_id": "Properti/Real Estat", "name_en": "Real Estate/Property"},
    {"slug": "construction", "name_id": "Konstruksi", "name_en": "Construction"},
    {"slug": "telecommunications", "name_id": "Telekomunikasi", "name_en": "Telecommunications"},
    {"slug": "automotive", "name_id": "Otomotif", "name_en": "Automotive"},
    {"slug": "mining", "name_id": "Pertambangan/Migas", "name_en": "Mining/Oil & Gas"},
    {"slug": "agriculture", "name_id": "Pertanian/Perkebunan", "name_en": "Agriculture/Plantation"},
    {"slug": "environment", "name_id": "Lingkungan/Keberlanjutan", "name_en": "Environmental/Sustainability"},
    {"slug": "insurance", "name_id": "Asuransi", "name_en": "Insurance"},
    {"slug": "consulting", "name_id": "Konsultansi", "name_en": "Consulting"},
    {"slug": "government", "name_id": "Pemerintahan/Sektor Publik", "name_en": "Government/Public Sector"},
    {"slug": "social_ngo", "name_id": "Sosial/NGO", "name_en": "Social Work/NGO"},
    {"slug": "fmcg", "name_id": "FMCG", "name_en": "FMCG"},
    {"slug": "aviation", "name_id": "Penerbangan", "name_en": "Aviation/Airlines"},
]
