LOCATIONS = [
    {"city": "Jakarta Selatan", "region": "Jabodetabek"},
    {"city": "Jakarta Pusat", "region": "Jabodetabek"},
    {"city": "Jakarta Barat", "region": "Jabodetabek"},
    {"city": "Jakarta Timur", "region": "Jabodetabek"},
    {"city": "Jakarta Utara", "region": "Jabodetabek"},
    {"city": "Tangerang", "region": "Jabodetabek"},
    {"city": "Bekasi", "region": "Jabodetabek"},
    {"city": "Depok", "region": "Jabodetabek"},
    {"city": "Bogor", "region": "Jabodetabek"},
    {"city": "Cikarang", "region": "Jabodetabek"},
    {"city": "Bandung", "region": "Jawa Barat"},
    {"city": "Surabaya", "region": "Jawa Timur"},
    {"city": "Semarang", "region": "Jawa Tengah"},
    {"city": "Yogyakarta", "region": "DIY"},
    {"city": "Solo", "region": "Jawa Tengah"},
    {"city": "Malang", "region": "Jawa Timur"},
    {"city": "Medan", "region": "Sumatera Utara"},
    {"city": "Palembang", "region": "Sumatera Selatan"},
    {"city": "Makassar", "region": "Sulawesi Selatan"},
    {"city": "Denpasar/Bali", "region": "Bali"},
    {"city": "Balikpapan", "region": "Kalimantan Timur"},
    {"city": "Batam", "region": "Kepulauan Riau"},
    {"city": "Remote / Anywhere", "region": None},
]
